name: hello-world

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Eltrovu, kiuj XML-dosieroj ŝanĝiĝis
      run: git show —name-only —summary —oneline formikita.. | grep "\.xml$" | uniq
    - name: Rezulto de antaŭa paŝo...
      #uses: docker://hello-world:latest
      run: cat
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
