name: test-needs-output

on:
  push:
    branches:
    - master  

jobs:

  j-1:
    runs-on: ubuntu-latest
    outputs:
      KONFIRMO: ${{ steps.set-konfirmo.outputs.KONFIRMO }}
      TESTO: ${{ steps.set-konfirmo.outputs.TESTO }}

    steps:
    - name: Kreu dosieron por testo ...
      run: |
        mkdir .log
        echo "\"rezulto\":\"konfirmo\"" > .log/mail_sent.log
        ls -l .log
        cat .log/mail_sent.log

    - name: Rigardu la protokolon 
      id: set-konfirmo
      run: |
        ls -l .log/
        # grep -l '\"konfirmo\"' .log/mail_sent*
        echo "KONFIRMO=$(if [[ $(grep -l '\"konfirmo\"' .log/mail_sent*) ]]; then echo "1"; fi)" >> $GITHUB_OUTPUT
        echo "TESTO=$(echo testo)" >> $GITHUB_OUTPUT
        # echo "::set-output name=KONFIRMO::$(grep -l '\"konfirmo\"' .log/mail_sent*)"
        # echo "::set-output name=TESTO::$(echo testo)"

    - name: Rigardu la variablon
      run: |
        echo "K: ${{steps.set-konfirmo.outputs.KONFIRMO}}"           
        echo "T: ${{steps.set-konfirmo.outputs.TESTO}}"           

  j-2:
    needs: j-1
    if: ${{needs.j-1.outputs.KONFIRMO}}
    runs-on: ubuntu-latest

    steps:
    - name: Rigardu la variablon
      run: |
        echo "K: ${{needs.j-1.outputs.KONFIRMO}}"           
        echo "T: ${{needs.j-1.outputs.TESTO}}"           
