name: test-needs-output

on:
  push:
    branches:
    - master  

jobs:

  j1:
    runs-on: ubuntu-latest
    outputs:
      KONFIRMO: ${{ steps.set_konfirmo.outputs.KONFIRMO }}
      TESTO: ${{ steps.set_konfirmo.outputs.TESTO }}

    steps:
    - name: Kreu dosieron por testo ...
      run: |
        mkdir .log
        echo "\"rezulto\":\"konfirmo\"" > .log/mail_sent.log
        ls -l .log
        cat .log/mail_sent.log

    - name: Rigardu la protokolon 
      id: set_konfirmo
      run: |
        ls -l .log/
        grep -l '\"konfirmo\"' .log/mail_sent*
        echo "::set-output name=KONFIRMO::$(grep -l '\"konfirmo\"' .log/mail_sent*)"
        echo "::set-output name=TESTO::$(echo testo)"

    - name: Rigardu la variablon
      run: |
        echo "K: ${{steps.set_konfirmo.outputs.KONFIRMO}}"           
        echo "T: ${{steps.set_konfirmo.outputs.TESTO}}"           

  j2:
    needs: j1
    runs-on: ubuntu-latest

    steps:
    - name: Rigardu la variablon
      run: |
        echo "K: ${{needs.j1.outputs.KONFIRMO}}"           
        echo "T: ${{needs.j1.outputs.TESTO}}"           
